FROM node:22-alpine
ENV NODE_ENV=production
WORKDIR /app
RUN apk add --no-cache docker-cli git
COPY package*.json ./
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY worker ./worker
CMD ["node", "worker/runner.mjs"]
