"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

type Deployment={id:string;status:string;branch:string|null;createdAt:string;logs:{id:string;level:string;message:string;timestamp:string}[]};
type Service={id:string;name:string;type:string;status:string;region:string;repository:string|null;branch:string|null;buildCommand:string|null;startCommand:string|null;port:number|null;deployments:Deployment[];domains:{id:string;hostname:string;verified:boolean;sslStatus:string}[]};
type Environment={id:string;name:string;kind:string;services:Service[]};
type Project={id:string;name:string;description:string|null;slug:string;environments:Environment[]};
const tabs=["Overview","Services","Deployments","Variables","Domains","Metrics","Activity"];
export default function ProjectWorkspace(){
 const params=useParams<{projectId:string}>();const projectId=params.projectId;
 const [project,setProject]=useState<Project|null>(null);const [tab,setTab]=useState("Overview");const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [adding,setAdding]=useState(false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 async function load(){setLoading(true);try{const r=await fetch(`/api/projects/${projectId}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load project");setProject(d.project);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load project");}finally{setLoading(false);}}
 useEffect(()=>{if(projectId)void load();},[projectId]);
 const services=project?.environments.flatMap(e=>e.services)||[];
 async function createService(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setNotice("");setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch(`/api/projects/${projectId}/services`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),type:f.get("type"),repository:f.get("repository"),branch:f.get("branch"),buildCommand:f.get("buildCommand"),startCommand:f.get("startCommand"),port:Number(f.get("port"))||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create service");setAdding(false);setNotice("Service configuration saved. Runtime is not connected, so no container has started.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not create service");}finally{setBusy(false);}}
 async function deploy(serviceId:string){setError("");setNotice("");setBusy(true);try{const r=await fetch(`/api/services/${serviceId}/deployments`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not queue deployment");setNotice("Deployment record created. It will remain queued until a build worker is connected.");await load();setTab("Deployments");}catch(e){setError(e instanceof Error?e.message:"Could not queue deployment");}finally{setBusy(false);}}
 if(loading)return <div className="p-8 text-sm text-slate-500">Loading project…</div>;
 if(!project)return <div className="p-8"><p className="text-red-300">{error||"Project not found."}</p><Link href="/dashboard/projects" className="mt-4 inline-block text-violet-300">← Projects</Link></div>;
 return <div className="space-y-6">
 <header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><Link href="/dashboard/projects" className="text-xs text-slate-500 hover:text-white">Projects</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">{project.name}</h1><span className="rounded-full border border-amber-300/20 bg-amber-300/[.04] px-3 py-1 text-xs text-amber-300">Runtime not connected</span></div><p className="mt-2 text-sm text-slate-400">{project.description||"Project workspace"} · Production · Lagos region</p></div><button onClick={()=>{setAdding(true);setTab("Services")}} className="h-10 rounded-xl bg-white px-4 text-sm font-semibold text-black">Add service</button></header>
 {error&&<p role="alert" className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-3 text-sm text-cyan-200">{notice}</p>}
 <nav className="flex gap-1 overflow-x-auto border-b border-white/10 pb-px">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm ${tab===t?"border-violet-400 text-white":"border-transparent text-slate-500 hover:text-slate-300"}`}>{t}</button>)}</nav>
 {tab==="Overview"&&<div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Services",String(services.length)],["Deployments",String(services.reduce((n,s)=>n+s.deployments.length,0))],["Domains",String(services.reduce((n,s)=>n+s.domains.length,0))],["Runtime","Not connected"]].map(([a,b])=><article key={a} className="rounded-2xl border border-white/10 bg-[#0d1016] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{a}</p><p className="mt-3 text-xl font-medium">{b}</p></article>)}</section><section className="rounded-2xl border border-white/10 bg-[#0d1016] p-6"><h2 className="font-medium">Environment topology</h2><p className="mt-1 text-xs text-slate-500">Stored configuration from the project database. Runtime state appears once a worker is connected.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{project.environments.map(env=><div key={env.id} className="rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between"><p className="font-medium">{env.name}</p><span className="text-xs text-slate-500">{env.kind}</span></div><p className="mt-2 text-xs text-slate-500">{env.services.length} configured services</p></div>)}</div></section></div>}
 {tab==="Services"&&<section className="space-y-4">{adding&&<form onSubmit={createService} className="grid gap-4 rounded-2xl border border-violet-400/20 bg-[#0d1016] p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-medium">Configure service</h2><label className="text-xs text-slate-400">Service name<input name="name" required minLength={2} maxLength={60} placeholder="web" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Type<select name="type" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"><option value="APPLICATION">Application</option><option value="WORKER">Worker</option><option value="CRON">Cron job</option><option value="STATIC">Static site</option><option value="DATABASE">Database (configuration only)</option></select></label><label className="text-xs text-slate-400 sm:col-span-2">Git repository URL<input name="repository" placeholder="https://github.com/owner/repository" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Branch<input name="branch" defaultValue="main" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Port<input name="port" type="number" min="1" max="65535" placeholder="3000" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Build command<input name="buildCommand" placeholder="npm run build" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Start command<input name="startCommand" placeholder="npm run start" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">{busy?"Saving…":"Save service"}</button><button type="button" onClick={()=>setAdding(false)} className="rounded-lg border border-white/10 px-4 py-2 text-sm">Cancel</button></div></form>}
 {services.length===0&&!adding&&<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center"><p className="text-sm text-slate-300">No services configured</p><p className="mt-2 text-xs text-slate-500">Add an application, worker, static site, cron job, or database configuration.</p><button onClick={()=>setAdding(true)} className="mt-4 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">Add first service</button></div>}
 {services.map(s=><article key={s.id} className="rounded-2xl border border-white/10 bg-[#0d1016] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-amber-400"/><h3 className="font-medium">{s.name}</h3><span className="rounded-md border border-white/10 px-2 py-1 text-[10px] text-slate-400">{s.type}</span></div><p className="mt-2 break-all text-xs text-slate-500">{s.repository||"No repository configured"}{s.branch? ` · ${s.branch}`:""}</p><p className="mt-2 text-xs text-amber-300">Configuration saved · runtime offline</p></div><button disabled={busy} onClick={()=>deploy(s.id)} className="h-9 rounded-lg border border-white/10 px-4 text-xs hover:bg-white/5 disabled:opacity-50">Queue deployment</button></div></article>)}</section>}
 {tab==="Deployments"&&<section className="space-y-3">{services.flatMap(s=>s.deployments.map(d=>({service:s.name,...d}))).length===0?<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No deployment records yet. Queue a deployment from a service when you are ready.</div>:services.flatMap(s=>s.deployments.map(d=>({service:s.name,...d}))).map(d=><article key={d.id} className="rounded-xl border border-white/10 bg-[#0d1016] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{d.service}</p><p className="mt-1 text-xs text-slate-500">{new Date(d.createdAt).toLocaleString()} · {d.branch||"no branch"}</p></div><span className="h-fit rounded-full border border-amber-400/20 px-3 py-1 text-xs text-amber-300">{d.status}</span></div>{d.logs.map(log=><p key={log.id} className="mt-3 text-xs text-slate-500">[{log.level}] {log.message}</p>)}</article>)}</section>}
 {tab==="Domains"&&<section className="rounded-2xl border border-dashed border-white/10 p-8 text-center"><p className="text-sm text-slate-300">Domain attachment is not enabled yet</p><p className="mt-2 text-xs text-slate-500">Domain records and HTTPS provisioning need an ingress controller and certificate automation.</p></section>}
 {tab==="Variables"&&<section className="rounded-2xl border border-dashed border-white/10 p-8 text-center"><p className="text-sm text-slate-300">Environment variable API is being prepared</p><p className="mt-2 text-xs text-slate-500">Secret values will not be displayed in the console after saving.</p></section>}
 {["Metrics","Activity"].includes(tab)&&<section className="rounded-2xl border border-dashed border-white/10 p-8 text-center"><p className="text-sm text-slate-300">{tab} require a connected runtime</p><p className="mt-2 text-xs text-slate-500">No fabricated metrics or activity events are shown.</p></section>}
 </div>;
}
