"use client";
import { ReactNode, useState } from "react";
import { useRouter, usePathname } from "next/navigation";
const links = [["Overview","/dashboard"],["Projects","/dashboard/projects"],["Deployments","/dashboard/deployments"],["Databases","/dashboard/databases"],["Domains","/dashboard/domains"],["Monitoring","/dashboard/monitoring"],["Billing","/dashboard/billing"],["Settings","/dashboard/settings"]];
export function AppShell({children,user}:{children:ReactNode;user:{name:string|null;email:string}}) {
  const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const router=useRouter(); const pathname=usePathname();
  async function logout(){setBusy(true);try{await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh();}finally{setBusy(false);}}
  return <div className="min-h-screen bg-[#08090b] text-white"><header className="fixed inset-x-0 top-0 z-40 h-16 border-b border-white/[.07] bg-[#08090b]/90 backdrop-blur-xl"><div className="flex h-full items-center justify-between px-5"><div className="flex items-center gap-3"><button onClick={()=>setOpen(!open)} className="rounded-lg border border-white/10 px-2 py-1.5 text-xs lg:hidden">Menu</button><a href="/dashboard" className="font-semibold tracking-wide">Reachmark</a><span className="hidden text-xs text-slate-600 sm:inline">/ Webhosting</span></div><div className="flex items-center gap-3 text-xs text-slate-400"><span className="hidden max-w-48 truncate sm:inline">{user.name || user.email}</span><button disabled={busy} onClick={logout} className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5">{busy?"Signing out…":"Sign out"}</button></div></div></header><aside className={`fixed bottom-0 left-0 top-16 z-30 w-64 border-r border-white/[.07] bg-[#0b0e12] p-4 transition-transform lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><nav className="space-y-1">{links.map(([name,href])=><a key={href} href={href} onClick={()=>setOpen(false)} className={`block rounded-lg px-3 py-2.5 text-sm ${pathname===href?"bg-white/[.07] text-white":"text-slate-400 hover:bg-white/[.04] hover:text-white"}`}>{name}</a>)}</nav><div className="absolute bottom-5 left-4 right-4 rounded-xl border border-white/[.07] p-3"><p className="text-xs font-medium">Runtime status</p><p className="mt-1 text-[11px] text-amber-300">Build worker not connected</p></div></aside><main className="pt-16 lg:pl-64">{children}</main></div>;
}
