"use client";
import { useEffect, useState } from "react";

type Connection={githubLogin:string;scopes:string;connectedAt:string};
type Repository={id:number;fullName:string;name:string;private:boolean;defaultBranch:string;htmlUrl:string;cloneUrl:string;updatedAt:string};
export function GitHubIntegration({status}:{status:string}) {
 const [connection,setConnection]=useState<Connection|null>(null);const [repos,setRepos]=useState<Repository[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 async function refresh(){setLoading(true);try{const r=await fetch("/api/integrations/github",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load GitHub status");setConnection(d.connection);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load GitHub status");}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 async function loadRepos(){setBusy(true);setError("");try{const r=await fetch("/api/integrations/github/repos",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Repository lookup failed");setRepos(d.repositories);}catch(e){setError(e instanceof Error?e.message:"Repository lookup failed");}finally{setBusy(false);}}
 async function disconnect(){setBusy(true);setError("");try{const r=await fetch("/api/integrations/github",{method:"DELETE"});if(!r.ok)throw new Error("Could not disconnect GitHub");setConnection(null);setRepos([]);}catch(e){setError(e instanceof Error?e.message:"Could not disconnect GitHub");}finally{setBusy(false);}}
 const statusMessage:Record<string,string>={"connected":"GitHub connected successfully.","not-configured":"GitHub OAuth is not configured. Add GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET, then set the callback URL.","state-error":"GitHub authorization state check failed. Please try again.","token-error":"GitHub did not return an access token.","profile-error":"Could not read the authorized GitHub profile.","connection-error":"GitHub connection failed. Check the server configuration.","signin-required":"Sign in before connecting GitHub."};
 return <section className="rounded-2xl border border-white/10 bg-[#0d1016] p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-violet-300">Source control</p><h2 className="mt-2 text-lg font-medium">GitHub</h2><p className="mt-2 max-w-xl text-sm text-slate-400">Authorize repository access to choose source repositories for your services. Tokens are encrypted before storage.</p></div>{!connection?<a href="/api/integrations/github/start" className="inline-flex h-10 items-center justify-center rounded-lg bg-white px-4 text-sm font-semibold text-black">Connect GitHub</a>:<div className="flex flex-wrap gap-2"><button onClick={loadRepos} disabled={busy} className="h-10 rounded-lg bg-white px-4 text-sm font-semibold text-black disabled:opacity-60">{busy?"Loading…":"List repositories"}</button><button onClick={disconnect} disabled={busy} className="h-10 rounded-lg border border-white/10 px-4 text-sm text-slate-300">Disconnect</button></div>}</div>
 {loading&&<p className="mt-5 text-sm text-slate-500">Checking connection…</p>}{connection&&<div className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/[.04] p-4"><p className="text-sm text-emerald-200">Connected as <strong>@{connection.githubLogin}</strong></p><p className="mt-1 text-xs text-slate-500">Connected {new Date(connection.connectedAt).toLocaleString()} · Granted scopes: {connection.scopes||"not reported"}</p></div>}
 {status&&statusMessage[status]&&<p className="mt-4 text-sm text-amber-300">{statusMessage[status]}</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}
 {repos.length>0&&<div className="mt-5"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">Accessible repositories</h3><span className="text-xs text-slate-500">{repos.length} loaded</span></div><div className="mt-3 max-h-96 space-y-2 overflow-auto">{repos.map(repo=><article key={repo.id} className="flex flex-col gap-3 rounded-xl border border-white/5 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><a href={repo.htmlUrl} target="_blank" rel="noreferrer" className="break-all text-sm font-medium text-slate-200 hover:text-violet-300">{repo.fullName}</a><p className="mt-1 text-xs text-slate-500">Default branch: {repo.defaultBranch} · {repo.private?"Private":"Public"}</p></div><button onClick={()=>navigator.clipboard.writeText(repo.cloneUrl)} className="h-8 shrink-0 rounded-lg border border-white/10 px-3 text-xs">Copy clone URL</button></article>)}</div></div>}
 </section>;
}
