"use client";
import { FormEvent, useEffect, useState } from "react";

type ServiceOption={id:string;name:string};
type Variable={id:string;key:string;isSecret:boolean;createdAt:string;updatedAt:string};
type Domain={id:string;hostname:string;verified:boolean;sslStatus:string;service:{id:string;name:string}};
export function ProjectConfiguration({projectId,mode,services}:{projectId:string;mode:"Variables"|"Domains";services:ServiceOption[]}) {
 const [variables,setVariables]=useState<Variable[]>([]);const [domains,setDomains]=useState<Domain[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 async function load(){setError("");try{const r=await fetch(`/api/projects/${projectId}/${mode.toLowerCase()}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load configuration");if(mode==="Variables")setVariables(d.variables||[]);else setDomains(d.domains||[]);}catch(e){setError(e instanceof Error?e.message:"Could not load configuration");}}
 useEffect(()=>{void load();},[projectId,mode]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setNotice("");const form=e.currentTarget;const f=new FormData(form);const payload=mode==="Variables"?{key:f.get("key"),value:f.get("value"),isSecret:true}:{hostname:f.get("hostname"),serviceId:f.get("serviceId")};
 try{const r=await fetch(`/api/projects/${projectId}/${mode.toLowerCase()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save configuration");form.reset();setNotice(mode==="Variables"?"Secret saved. The plaintext value will not be shown again.":"Domain record saved. DNS and HTTPS are still pending runtime infrastructure.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not save configuration");}finally{setBusy(false);}}
 return <div className="space-y-4"><form onSubmit={submit} className="grid gap-4 rounded-2xl border border-white/10 bg-[#0d1016] p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-medium">{mode==="Variables"?"Add environment variable":"Attach a domain"}</h2>{mode==="Variables"?<><label className="text-xs text-slate-400">Key<input name="key" required pattern="[A-Z_][A-Z0-9_]{0,127}" placeholder="API_BASE_URL" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Value<input name="value" required maxLength={10000} type="password" autoComplete="new-password" placeholder="Secret value" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label></>:<><label className="text-xs text-slate-400">Hostname<input name="hostname" required placeholder="app.example.com" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white"/></label><label className="text-xs text-slate-400">Service<select name="serviceId" required className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-[#0a0c10] px-3 text-sm text-white"><option value="">Choose a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></>}<div className="sm:col-span-2"><button disabled={busy||(mode==="Domains"&&services.length===0)} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{busy?"Saving…":mode==="Variables"?"Save encrypted variable":"Add domain record"}</button></div></form>
 {error&&<p role="alert" className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-3 text-sm text-cyan-200">{notice}</p>}
 {mode==="Variables"&&<section className="rounded-2xl border border-white/10 bg-[#0d1016] p-5"><h3 className="font-medium">Stored variables</h3><p className="mt-1 text-xs text-slate-500">Only keys and metadata are listed; values are never returned.</p>{variables.length===0?<p className="mt-5 text-sm text-slate-500">No variables saved.</p>:<div className="mt-4 divide-y divide-white/5">{variables.map(v=><div key={v.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-mono text-sm">{v.key}</p><p className="mt-1 text-xs text-slate-600">Updated {new Date(v.updatedAt).toLocaleString()}</p></div><span className="rounded-full border border-emerald-400/20 px-3 py-1 text-xs text-emerald-300">Encrypted</span></div>)}</div>}</section>}
 {mode==="Domains"&&<section className="rounded-2xl border border-white/10 bg-[#0d1016] p-5"><h3 className="font-medium">Domain records</h3>{domains.length===0?<p className="mt-5 text-sm text-slate-500">No domains attached.</p>:<div className="mt-4 divide-y divide-white/5">{domains.map(d=><div key={d.id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{d.hostname}</p><p className="mt-1 text-xs text-slate-500">Service: {d.service.name}</p></div><span className="h-fit rounded-full border border-amber-400/20 px-3 py-1 text-xs text-amber-300">DNS / TLS pending</span></div>)}</div>}</section>}
 </div>;
}
