"use client";

import { motion } from "framer-motion";

const nodes=[
  {id:"web",label:"Web",type:"Application",x:"12%",y:"46%"},
  {id:"api",label:"API",type:"Service",x:"38%",y:"27%"},
  {id:"worker",label:"Worker",type:"Background job",x:"38%",y:"70%"},
  {id:"db",label:"PostgreSQL",type:"Database",x:"70%",y:"27%"},
  {id:"redis",label:"Redis",type:"Cache / queue",x:"70%",y:"70%"}
];

export function InfrastructureGraph(){return <section className="bg-[#050609] px-6 py-32 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs uppercase tracking-[.24em] text-violet-300">Project canvas</p><h2 className="mt-5 text-4xl tracking-[-.05em] sm:text-6xl">Your architecture, visible at a glance.</h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-400">Projects group services into one network-aware workspace. See your application, API, workers, databases, and cache as one system.</p><div className="mt-8 flex flex-wrap gap-2 text-xs text-slate-400"><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2">Drag to arrange</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2">Click to inspect</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2">Deploy from canvas</span></div></div><div className="relative min-h-[520px] overflow-hidden rounded-3xl border border-white/10 bg-[#080b10] shadow-2xl"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] [background-size:36px_36px]"/><svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M18 50 L42 30 L74 30 M42 30 L42 70 L74 70" fill="none" stroke="rgba(139,92,246,.45)" strokeWidth=".35"/><path d="M42 30 L74 70" fill="none" stroke="rgba(34,211,238,.28)" strokeDasharray="1 1" strokeWidth=".3"/></svg>{nodes.map((n,i)=><motion.div key={n.id} initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-60px"}} transition={{delay:i*.08}} className="absolute w-[150px] -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-white/10 bg-[#0d1118]/95 p-4 shadow-xl backdrop-blur" style={{left:n.x,top:n.y}}><div className="flex items-center justify-between"><span className="text-sm font-medium">{n.label}</span><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_rgba(74,222,128,.8)]"/></div><p className="mt-2 text-[11px] text-slate-500">{n.type}</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/5"><div className="h-full w-2/3 rounded-full bg-violet-400/60"/></div></motion.div>)}</div></div></div></section>}