import Link from "next/link";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function DeploymentsPage() {
 const user=await getCurrentUser();const workspaceId=user?.memberships[0]?.workspaceId;
 const deployments=workspaceId?await prisma.deployment.findMany({where:{service:{project:{workspaceId}}},include:{service:{include:{project:true}},logs:{orderBy:{timestamp:"asc"},take:20}},orderBy:{createdAt:"desc"},take:100}):[];
 return <div className="space-y-8"><header><p className="text-xs uppercase tracking-[.22em] text-violet-300">Delivery</p><h1 className="mt-2 text-3xl font-semibold">Deployments</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Deployment records across your projects. Queued records do not run until a build worker is configured.</p></header>
 {deployments.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center"><p className="text-sm text-slate-300">No deployment records yet</p><p className="mt-2 text-xs text-slate-500">Create a project and service to start tracking a deployment.</p><Link href="/dashboard/projects" className="mt-4 inline-flex rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">View projects</Link></div>:<section className="space-y-3">{deployments.map(d=><article key={d.id} className="rounded-2xl border border-white/10 bg-[#0d1016] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><Link href={`/dashboard/projects/${d.service.projectId}`} className="font-medium hover:text-violet-300">{d.service.project.name} / {d.service.name}</Link><p className="mt-1 text-xs text-slate-500">{new Date(d.createdAt).toLocaleString()} · {d.branch||"no branch"}{d.commitSha? ` · ${d.commitSha.slice(0,7)}`:""}</p></div><span className="h-fit rounded-full border border-amber-300/20 px-3 py-1 text-xs text-amber-300">{d.status}</span></div>{d.logs.map(log=><p key={log.id} className="mt-3 text-xs text-slate-500">[{log.level}] {log.message}</p>)}</article>)}</section>}</div>;
}
