import Link from "next/link";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function DashboardPage(){
 const user=await getCurrentUser();const workspaceId=user?.memberships[0]?.workspaceId;
 const since=new Date();since.setDate(1);since.setHours(0,0,0,0);
 const [projects,activeServices,monthDeployments,recentProjects]=workspaceId?await Promise.all([
  prisma.project.count({where:{workspaceId}}),
  prisma.service.count({where:{project:{workspaceId},status:"HEALTHY"}}),
  prisma.deployment.count({where:{service:{project:{workspaceId}},createdAt:{gte:since}}}),
  prisma.project.findMany({where:{workspaceId},include:{_count:{select:{services:true}}},orderBy:{updatedAt:"desc"},take:5})
 ]):[0,0,0,[]];
 return <div className="p-6 sm:p-8 lg:p-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.22em] text-violet-300">Workspace</p><h1 className="mt-3 text-3xl tracking-[-.04em]">Overview</h1><p className="mt-2 text-sm text-slate-500">Your saved projects and control-plane activity.</p></div><Link href="/dashboard/projects/new" className="inline-flex h-10 items-center rounded-lg bg-white px-4 text-sm font-semibold text-black">New project</Link></div>
 <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Projects",String(projects)],["Healthy services",String(activeServices)],["Deployments this month",String(monthDeployments)],["Hosting runtime","Not connected"]].map(([label,value])=><article key={label} className="rounded-2xl border border-white/[.08] bg-[#101216] p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-3 text-2xl">{value}</p><p className="mt-2 text-[11px] text-slate-600">{label==="Hosting runtime"?"Build worker and container runtime unavailable":"Live database records"}</p></article>)}</div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><section className="rounded-2xl border border-white/[.08] bg-[#101216] p-6"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[.18em] text-slate-500">Recent projects</p><Link href="/dashboard/projects" className="text-xs text-violet-300">View all →</Link></div>{recentProjects.length===0?<div className="mt-6 rounded-xl border border-dashed border-white/10 p-10 text-center"><p className="text-sm text-slate-300">No projects yet</p><p className="mt-2 text-xs text-slate-600">Create a project to start configuring services.</p><Link href="/dashboard/projects/new" className="mt-5 inline-flex rounded-lg bg-white px-4 py-2 text-xs font-semibold text-black">Create project</Link></div>:<div className="mt-4 divide-y divide-white/5">{recentProjects.map(p=><Link key={p.id} href={`/dashboard/projects/${p.id}`} className="flex items-center justify-between gap-3 py-4 hover:text-violet-300"><div><p className="text-sm font-medium">{p.name}</p><p className="mt-1 text-xs text-slate-500">{p._count.services} configured services</p></div><span className="text-slate-500">→</span></Link>)}</div>}</section>
 <section className="rounded-2xl border border-white/[.08] bg-[#101216] p-6"><p className="text-xs uppercase tracking-[.18em] text-slate-500">Quick actions</p><div className="mt-6 space-y-2">{[["Create project","/dashboard/projects/new"],["Connect GitHub","/dashboard/settings"],["View deployments","/dashboard/deployments"],["Configure domains","/dashboard/domains"]].map(([label,href])=><Link key={href} href={href} className="block w-full rounded-xl border border-white/[.07] px-4 py-3 text-sm text-slate-300 hover:bg-white/[.03]">{label} <span className="float-right text-slate-600">→</span></Link>)}</div></section></div></div></div>;
}
